### PR TITLE
updated documentation to reflect latest understanding of gbp

### PR DESCRIPTION
**Pull request by berndpfrommer**
updated documentation as I understand the gbp process better

### CODE REVIEW

**Comment by jlblancoc** [comment]
Brilliant! Will try it out soon.

Any pointer on how to use gbp to release nightly builds, eg using the date+git commit hash as version postfix (after a ~)? If not I'll investigate it, don't worry.

**Comment by berndpfrommer** [comment]
I have not started working yet on the version stuff. I can look into it, but it will take a few days.
I just pushed the branches with the debian packaging and the pristine tar balls. I have to leave any second, will hopefully be able to work on it more tonight and tomorrow.

**Comment by berndpfrommer** [comment]
Added some documentation outlining how to do snapshots.
The one thing I have not had time to automate yet is the dpkg-source --commit. It asks for a commit message. Will look into it over the next few days. Also need more time to package the instructions into a working script that can run on a nightly basis.
Question along those lines: does GTSAM have continuous integration (CI) set up yet?

**Comment by jlblancoc** [comment]
Thanks! @berndpfrommer 

> Question along those lines: does GTSAM have continuous integration (CI) set up yet?

Yes, sure: Travis is working, and they were recently testing GitHub Actions...

**Pull request merged**
